import { useComputed, useSignal } from "@preact/signals";
import { useEffect } from "preact/hooks";
import { IS_BROWSER } from "fresh/runtime";

interface WH {
  id: string;
  name: string;
  url: string;
}
interface Props {
  /** The User's Size Unit, to label the "size" input correctly. */
  sizeUnit: string;
}

/** TradingView's webhook source IPs — these must be on the webhook's allowlist. */
const TV_IPS = ["52.89.214.238", "34.212.75.30", "54.218.53.128", "52.32.178.7"];

interface PineConfig {
  symbol: string;
  size: string;
  leverage: string;
  takeProfit: string;
  stopLoss: string;
  sendClientId: boolean;
  url: string;
}

/**
 * A complete, ready-to-paste Pine v6 strategy. Webhook sends are driven by the
 * alert() function (the message is delivered to the webhook verbatim — no fragile
 * {{placeholder}} expansion inside alert_message), while strategy.entry/close keep
 * the backtest curve meaningful. The secret is read from the script's Inputs, so
 * it never gets baked into copied/shared code.
 */
function buildPine(c: PineConfig): string {
  const tpsl = (c.takeProfit ? `,"takeProfit":"${c.takeProfit}"` : "") +
    (c.stopLoss ? `,"stopLoss":"${c.stopLoss}"` : "");
  const urlComment = c.url
    ? `// Webhook URL (paste into the alert's Notifications -> Webhook URL):\n//   ${c.url}\n`
    : "";
  // NOTE: keep this script ASCII-only. Non-ASCII characters (even in comments)
  // can trip Pine's lexer ("Syntax error at input ..."), so no box-drawing/arrows.
  return `//@version=6
// -----------------------------------------------------------------------------
// Hookshot -> Ostium webhook trader  (generated by your Hookshot dashboard)
//
// Paste into TradingView's Pine Editor, "Add to chart", then create an alert with
// condition = this strategy + "alert() function calls only" (see the app's steps).
// Your secret lives in Settings -> Inputs (below), NOT in this code, so the script
// stays safe to share.
${urlComment}// -----------------------------------------------------------------------------
strategy("Hookshot Ostium ${c.symbol}", overlay = true, calc_on_every_tick = false, pyramiding = 1)

// Hookshot config
secret       = input.string("<secret>", "Hookshot secret (paste yours here)")
ostiumSymbol = input.string("${c.symbol}", "Ostium symbol (e.g. BTC/USD)")
posSize      = input.string("${c.size}", "Size (in your Size Unit)")
leverage     = input.string("${c.leverage}", "Leverage")
sendClientId = input.bool(${c.sendClientId}, "Send clientId (dedupes alert retries)")

// Example signal: fast/slow SMA cross. REPLACE this block with your own logic.
fastLen = input.int(9, "Fast MA length")
slowLen = input.int(21, "Slow MA length")
fast = ta.sma(close, fastLen)
slow = ta.sma(close, slowLen)
longSignal  = ta.crossover(fast, slow)
shortSignal = ta.crossunder(fast, slow)
plot(fast, "Fast MA", color.new(#ff5a19, 0))
plot(slow, "Slow MA", color.new(#808080, 0))

// Build Hookshot JSON (single-quoted Pine strings so JSON double quotes are literal)
cid(action, dir) => sendClientId ? ',"clientId":"' + action + '-' + dir + '-' + str.tostring(time) + '"' : ''
openMsg(dir)  => '{"secret":"' + secret + '","action":"open","symbol":"' + ostiumSymbol + '","direction":"' + dir + '","size":"' + posSize + '","leverage":"' + leverage + '","orderType":"market"${tpsl}' + cid("open", dir) + '}'
closeMsg(dir) => '{"secret":"' + secret + '","action":"close","symbol":"' + ostiumSymbol + '","direction":"' + dir + '","size":"all"' + cid("close", dir) + '}'

// On confirmed bar closes: reverse position (backtest) + fire webhook alerts
if longSignal and strategy.position_size <= 0
    if strategy.position_size < 0
        strategy.close("Short", alert_message = closeMsg("short"))
        alert(closeMsg("short"), alert.freq_once_per_bar_close)
    strategy.entry("Long", strategy.long, alert_message = openMsg("long"))
    alert(openMsg("long"), alert.freq_once_per_bar_close)

if shortSignal and strategy.position_size >= 0
    if strategy.position_size > 0
        strategy.close("Long", alert_message = closeMsg("long"))
        alert(closeMsg("long"), alert.freq_once_per_bar_close)
    strategy.entry("Short", strategy.short, alert_message = openMsg("short"))
    alert(openMsg("short"), alert.freq_once_per_bar_close)
`;
}

/** A human-readable preview of the JSON the script POSTs (clientId omitted). */
function previewMessages(c: PineConfig): string {
  const tpsl = (c.takeProfit ? `,"takeProfit":"${c.takeProfit}"` : "") +
    (c.stopLoss ? `,"stopLoss":"${c.stopLoss}"` : "");
  const open =
    `{"secret":"<secret>","action":"open","symbol":"${c.symbol}","direction":"long","size":"${c.size}","leverage":"${c.leverage}","orderType":"market"${tpsl}}`;
  const close =
    `{"secret":"<secret>","action":"close","symbol":"${c.symbol}","direction":"long","size":"all"}`;
  return `open long  →  ${open}\nclose long  →  ${close}`;
}

export default function PineScript({ sizeUnit }: Props) {
  const list = useSignal<WH[]>([]);
  const sel = useSignal("");
  const symbol = useSignal("BTC/USD");
  const size = useSignal("0.01");
  const leverage = useSignal("10");
  const takeProfit = useSignal("");
  const stopLoss = useSignal("");
  const sendClientId = useSignal(true);
  const copied = useSignal("");
  const ipMsg = useSignal("");

  async function load() {
    const r = await fetch("/api/webhooks");
    if (!r.ok) return;
    const webhooks = (await r.json()).webhooks as WH[];
    list.value = webhooks;
    if (!webhooks.find((w) => w.id === sel.value)) sel.value = webhooks[0]?.id ?? "";
  }

  useEffect(() => {
    if (!IS_BROWSER) return;
    load();
    const onChange = () => load();
    globalThis.addEventListener("hookshot:webhooks-changed", onChange);
    return () => globalThis.removeEventListener("hookshot:webhooks-changed", onChange);
  }, []);

  const url = useComputed(() => list.value.find((w) => w.id === sel.value)?.url ?? "");
  const unitLabel = sizeUnit === "usd_collateral"
    ? "USD collateral"
    : sizeUnit === "usd_notional"
    ? "USD notional"
    : "base asset";

  const cfg = useComputed<PineConfig>(() => ({
    symbol: symbol.value || "BTC/USD",
    size: size.value || "0.01",
    leverage: leverage.value || "10",
    takeProfit: takeProfit.value.trim(),
    stopLoss: stopLoss.value.trim(),
    sendClientId: sendClientId.value,
    url: url.value,
  }));
  const script = useComputed(() => buildPine(cfg.value));
  const preview = useComputed(() => previewMessages(cfg.value));

  async function copy(text: string, which: string) {
    try {
      await navigator.clipboard.writeText(text);
      copied.value = which;
      setTimeout(() => (copied.value = ""), 1500);
    } catch {
      copied.value = "";
    }
  }

  /** Add TradingView's webhook IPs to the selected webhook's allowlist (skips any already present). */
  async function allowlistTradingView() {
    const id = sel.value;
    if (!id) return;
    ipMsg.value = "Adding…";
    let existing: { cidr: string }[] = [];
    try {
      const r = await fetch(`/api/webhooks/${id}`);
      if (r.ok) existing = (await r.json()).ips ?? [];
    } catch {
      // fall through - we'll just attempt all four
    }
    const have = new Set(existing.map((ip) => ip.cidr.replace(/\/32$/, "")));
    let added = 0;
    for (const ip of TV_IPS) {
      if (have.has(ip)) continue;
      const res = await fetch(`/api/webhooks/${id}/ips`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ cidr: ip, label: "TradingView" }),
      });
      if (res.ok) added += 1;
    }
    ipMsg.value = added > 0
      ? `Added ${added} TradingView IP${added === 1 ? "" : "s"} to "${
        list.value.find((w) => w.id === id)?.name
      }". ${TV_IPS.length - added} already present.`
      : "All TradingView IPs were already allowlisted.";
    if (IS_BROWSER) globalThis.dispatchEvent(new CustomEvent("hookshot:webhooks-changed"));
  }

  if (list.value.length === 0) {
    return (
      <div class="panel">
        <h3 class="accent">TradingView Pine Script</h3>
        <p class="muted">Create a webhook above first, then come back to generate your script.</p>
      </div>
    );
  }

  return (
    <div class="panel">
      <h3 class="accent">TradingView Pine Script</h3>
      <p class="muted">
        Generate a Pine v6 <strong>strategy</strong>{" "}
        that fires your trades at this webhook. It sends market orders via Pine's{" "}
        <code>alert()</code>{" "}
        function, so the JSON reaches Hookshot exactly as written. Replace the example
        moving-average cross with your own entry logic.
      </p>

      <div class="row">
        <label>
          <span class="muted">Webhook</span>{" "}
          <select
            value={sel.value}
            onChange={(e) => (sel.value = (e.target as HTMLSelectElement).value)}
          >
            {list.value.map((w) => <option value={w.id} key={w.id}>{w.name}</option>)}
          </select>
        </label>
        <label>
          <span class="muted">Symbol</span>{" "}
          <input
            value={symbol.value}
            placeholder="BTC/USD"
            onInput={(e) => (symbol.value = (e.target as HTMLInputElement).value)}
          />
        </label>
        <label>
          <span class="muted">Size ({unitLabel})</span>{" "}
          <input
            value={size.value}
            onInput={(e) => (size.value = (e.target as HTMLInputElement).value)}
          />
        </label>
        <label>
          <span class="muted">Leverage</span>{" "}
          <input
            value={leverage.value}
            onInput={(e) => (leverage.value = (e.target as HTMLInputElement).value)}
          />
        </label>
      </div>

      <div class="row" style="margin-top:12px">
        <label>
          <span class="muted">Take profit (optional)</span>{" "}
          <input
            value={takeProfit.value}
            placeholder="75000"
            onInput={(e) => (takeProfit.value = (e.target as HTMLInputElement).value)}
          />
        </label>
        <label>
          <span class="muted">Stop loss (optional)</span>{" "}
          <input
            value={stopLoss.value}
            placeholder="60000"
            onInput={(e) => (stopLoss.value = (e.target as HTMLInputElement).value)}
          />
        </label>
        <label class="row" style="gap:6px">
          <input
            type="checkbox"
            checked={sendClientId.value}
            onChange={(e) => (sendClientId.value = (e.target as HTMLInputElement).checked)}
          />
          <span class="muted">Send clientId (recommended)</span>
        </label>
      </div>
      {!sendClientId.value
        ? (
          <p class="muted">
            ⚠ Without a clientId, two identical signals within 10s look like a duplicate and the
            second is dropped — keep this on unless you have a reason not to.
          </p>
        )
        : null}

      <h4>1. Allowlist TradingView</h4>
      <p class="muted">
        TradingView posts from fixed IPs. A fresh webhook denies all IPs, so add them or your alerts
        are silently rejected (403).
      </p>
      <div class="row">
        <button type="button" onClick={allowlistTradingView}>Allowlist TradingView's IPs</button>
        <span class="muted mono">{TV_IPS.join(", ")}</span>
      </div>
      {ipMsg.value ? <p class="muted">{ipMsg.value}</p> : null}

      <h4>2. Copy the script</h4>
      <pre>{script.value}</pre>
      <div class="row">
        <button type="button" onClick={() => copy(script.value, "script")}>
          {copied.value === "script" ? "Copied ✓" : "Copy Pine script"}
        </button>
      </div>

      <h4>3. Create the alert</h4>
      <ol class="muted" style="line-height:24px">
        <li>
          In TradingView open the <strong>Pine Editor</strong>, paste the script, hit{" "}
          <strong>Save</strong>, then <strong>Add to chart</strong>.
        </li>
        <li>
          Open the strategy's <strong>Settings → Inputs</strong> and paste your real{" "}
          <strong>Hookshot secret</strong> (and confirm symbol / size / leverage).
        </li>
        <li>
          Click the alarm icon → <strong>Create Alert</strong>. Set <strong>Condition</strong>{" "}
          to this strategy and choose <strong>"alert() function calls only"</strong>.
        </li>
        <li>
          Under <strong>Notifications</strong>, enable <strong>Webhook URL</strong> and paste:
        </li>
      </ol>
      <p class="mono">{url.value}</p>
      <div class="row">
        <button type="button" class="secondary" onClick={() => copy(url.value, "url")}>
          {copied.value === "url" ? "Copied ✓" : "Copy webhook URL"}
        </button>
      </div>
      <p class="muted" style="margin-top:8px">
        Set the alert <strong>Expiration</strong> to <strong>Open-ended</strong>{" "}
        and create it. Each signal then POSTs to Hookshot — watch it land in{" "}
        <strong>Signals &amp; orders</strong> above.
      </p>

      <h4>What it sends</h4>
      <pre>{preview.value}</pre>
      <p class="muted">
        Need limit/stop orders, modify, or cancel? Build those bodies in{" "}
        <strong>Build a trade</strong> below and drop them into your own <code>alert()</code> calls.
      </p>
    </div>
  );
}
